name: buildpush

on:
  push:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get tag name
        run: |
          if [[ "${{ env.BRANCH_NAME }}" == "master" ]]; then
            echo "Setting tag name to latest"
            echo "TAG_NAME=latest" >> $GITHUB_ENV
          elif [[ "${{ env.BRANCH_NAME }}" =~ ^refs/tags/.* ]]; then
            tName="${{ env.BRANCH_NAME }}"
            echo "Setting tag name to ${tName#refs/tags/}"
            echo "TAG_NAME=${tName#refs/tags/}" >> $GITHUB_ENV
          else
            echo "Setting tag name to ${{ env.BRANCH_NAME }}"
            echo "TAG_NAME=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
          fi
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: alchen99/k8s-debug:${{ env.TAG_NAME }}
